from selenium.webdriver.common.by import By

first_name_field = (By.XPATH, "(//input[@name='firstname'])[1]")
last_name_field = (By.XPATH, "(//input[@name='firstname'])[2]")
dob_calender = (By.XPATH, "//input[@id='birthday']")
male_radio_button = (By.ID, "male")
num_passenger_dropdown = (By.ID, "admorepass")
one_way_radio_button = (By.ID, "oneway")
from_city_field = (By.ID, "fromcity")
dest_city_field = (By.ID, "destcity")
depart_date_calender = (By.ID, "departdate")
return_date_calender = (By.ID, "returndate")
billing_name_field= (By.ID, "billing_name")
phone_field = (By.ID, "billing_phone")
email_field = (By.ID, "billing_email")
address_field= (By.ID, "billing_address")
country_dropdown = (By.ID, "billing_country")
postcode_field= (By.ID, "postcode")
street_address_field = (By.ID, "street_address1")
most_visited_cities_radio_btn = (By.XPATH, "(//input[@type='checkbox'])[2]")