# 1.one way = //p[text()="One-way"]
# round trip= //p[text()="Round-trip"]
# multi city = //p[text()="Multi-city"]
# from = //span[text()="From"]
# to = //span[text()="To"]
# departure - //span[text()="Departure"]
# return = //span[text()="Return"]
# traveler and details = //span[text()="Travellers & Class"]
# manage booking = //p[text()="Manage Booking"]
# holiday = //span[text()="Holidays"]
# viewall = //span[text()="View All"]
# search flight = //span[text()="SEARCH FLIGHTS"]