import time

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import  expected_conditions as ec

driver = webdriver.Chrome()
driver.maximize_window()
driver.get("https://automationbysqatools.blogspot.com/2021/05/dummy-website.html")
wait = WebDriverWait(driver, timeout=30)
time.sleep(1)
def web_element(locator):
    return wait.until(ec.visibility_of_element_located(locator))

time.sleep(3)
sqa_tools = web_element(locator=(By.CSS_SELECTOR, '#Header1_headerimg')) # SQA Tools
print(sqa_tools.text)
dummy_website = web_element(locator=(By.CSS_SELECTOR, ".post-title.entry-title"))
print(dummy_website.text)
time.sleep(3)
choose_option = web_element(locator=(By.XPATH, "//*[text()='Choose the correct option:']"))
print(choose_option.text)
time.sleep(3)
first_name = web_element(locator=(By.XPATH, "(//input[@name='firstname'])[1]")).send_keys("Pritam")
last_name = web_element(locator=(By.XPATH, "(//input[@name='firstname'])[2]")).send_keys("Pawan")
time.sleep(4)
# gender = web_element(locator=(By.ID, "male")).click()
gender = web_element(locator=(By.XPATH, '//input[@id="male"]')).click()
# round_trip = web_element(locator=(By.ID, 'roundtrip')).click()
time.sleep(2)
roundtrip = web_element(locator=(By.XPATH, '//input[@id="oneway"]')).click()
roundtrip = web_element(locator=(By.XPATH, '//input[@id="roundtrip"]')).click()
time.sleep(2)
# from_city = web_element(locator=(By.ID, 'fromcity')).send_keys("Bangalore")
from_city = web_element(locator=(By.XPATH,'//input[@name="fromcity"]')).send_keys("Bangalore")
# dest_city = web_element(locator=(By.ID, 'destcity')).send_keys("Pune")
dest_city = web_element(locator=(By.XPATH,'//input[@name="destcity"]')).send_keys("Pune")
time.sleep(1)
depart_date = web_element(locator=(By.XPATH,'//input[@name="departdate"]')).send_keys("12-09-2024")
return_date = web_element(locator=(By.XPATH,'//input[@name="returndate"]')).send_keys("14-09-2024")
# depart_date = web_element(locator=(By.ID, 'departdate')).send_keys("14/09/2024")
# return_date = web_element(locator=(By.ID, 'returndate')).send_keys("14/09/2024")
dept_date = web_element(locator=(By.CSS_SELECTOR, 'input[name="departdate"]')).send_keys("10/09/2024")
return_date = web_element(locator=(By.CSS_SELECTOR, 'input[name="returndate"]')).send_keys("12/09/2024")
time.sleep(1)
# visa = web_element(locator=(By.ID, "visadate")).send_keys("12/09/2024")
visa = web_element(locator=(By.XPATH,'//input[@id="visadate"]')).send_keys("14-09-2024")
time.sleep(1)
# billing_name = web_element(locator=(By.ID, "billing_name")).send_keys("Pritam Pawan")
billing_name = web_element(locator=(By.XPATH,'//input[@id="billing_name"]')).send_keys("Pritam Pawan")
# billing_phone = web_element(locator=(By.ID, "billing_phone")).send_keys("7760168991")
billing_phone = web_element(locator=(By.ID, "billing_phone")).send_keys("7760168991")
# billing_name = web_element(locator=(By.XPATH,'//input[@id="billing_phone"]')).send_keys("7760168991")
# email = web_element(locator=(By.ID, "billing_email")).send_keys("p09@gmail.com")
email = web_element(locator=(By.XPATH,'//input[@id="billing_email"]')).send_keys("p09@gmail.com")
# address = web_element(locator=(By.ID, "billing_address")).send_keys("#16 HAL, Bangalore")
address = web_element(locator=(By.XPATH,'//input[@id="billing_address"]')).send_keys("Hsr Bangalore")
country = web_element(locator=(By.ID, "billing_country")).click()
# postcode = web_element(locator=(By.ID, "postcode")).send_keys("560037")
postcode = web_element(locator=(By.XPATH,'//input[@id="postcode"]')).send_keys("560037")
# prefecture = web_element(locator=(By.ID, "prefecture")).send_keys("1234")
prefecture = web_element(locator=(By.XPATH,'//input[@name="prefecture"]')).send_keys("1234")
street_address = web_element(locator=(By.ID, "street_address1")).send_keys("HSR, Bangalore")
time.sleep(1)
city_opt1 = web_element(locator=(By.XPATH, "(//input[@type='checkbox'])[1]")).click()
Contact_Form = driver.find_element(By.XPATH,"//input[@id='ContactForm2_contact-form-name']").send_keys("Pritam Pawan")
Contact_Form_Email = driver.find_element(By.XPATH,"//input[@id='ContactForm2_contact-form-email']").send_keys("p09@gmail.com")
Contact_Form_Message = driver.find_element(By.XPATH,"(//textarea[@class='contact-form-email-message'])[1]").send_keys("Most Welcome")
Contact_Form_Submit = driver.find_element(By.XPATH,"//input[@id='ContactForm2_contact-form-submit']").click()
driver.save_screenshot("C:\\test_images\\country_png.png")
pass_dd_elem = driver.find_element(By.ID,"admorepass")
pass_dd_elem.screenshot("C:\\test_images\\add_more_passenger.png")

time.sleep(1)
driver.close()



