import time
from selenium import webdriver
from selenium.webdriver .common.by import By

driver = webdriver.chrome()
driver.maximize.window()
driver.implicitly.wat(20)
driver.get("https://automationbysqatools.blogspot.com/2021/05/dummy-website.html")
driver.findelement(By.NAME,"Dummy Website").click()
Header = driver.findelement(By.TAG_NAME," Dummy Ticket Booking Website")
print("Header name:,"Header.text)
driver.findelement(By.NAME,"firstname").sendkeys("Pritam")
driver.findelement(By.NAME,)
driver.findelement(By.ID,"birthday").sendkeys('09-05-1991')
driver.findelement(By.ID,"male")
print(("check element is displayed:",element.is_displayed()))
print(("check element is selected before click:"),element .is_selected())
print("check element is displayed:",element.click())
print(("check element is selected after click:",element.is_selected()))
print("check element is enabled:",element.is_enabled())
driver.findelement(By.ID,"female")
print(("check element is displayed:",element.is_displayed()))
print(("check element is selected before click:"),element .is_selected())
print("check element is displayed:",element.click())
print(("check element is selected after click:",element.is_selected()))
print("check element is enabled:",element.is_enabled())
